.\" GNOME Video Arcade manpage.
.\" Copyright © 2007 Matthew Barnes
.\"
.TH GNOME-VIDEO-ARCADE "1" "October 2007" "GNOME" ""
.SH NAME
gnome-video-arcade \- A MAME front-end for GNOME 
.SH SYNOPSIS
.B gnome-video-arcade
[\fIOPTION\fR...]
.SH DESCRIPTION
.B gnome-video-arcade
is a MAME front-end for the GNOME Desktop Environment.  It supports both the
.B xmame
and
.B sdlmame
ports of the original MAME program written by Nicola Salmoria.
.P
This program is targeted towards non-technical arcade enthusiasts who just
want to easily play classic arcade games on their desktop.  Though it may
be suitable for use in custom arcade cabinets,
.B gnome-video-arcade
is not designed for that purpose.
.SH OPTIONS
.TP
\fB\-?\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-b\fR, \fB\-\-build-database\fR
Build the games database
.TP
\fB\-v\fR, \fB\-\-version\fR
Show the application version
.TP
\fB\-w\fR, \fB\-\-which-emulator\fR
Show which emulator will be used
.TP
\fB\-\-display\fR
X display to use
.SH AUTHOR
Written by Matthew Barnes <mbarnes@redhat.com>
