/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 117
#define YY_END_OF_BUFFER 118
static yyconst short int yy_accept[364] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  118,  116,
      112,  114,  116,   76,  116,  116,  116,   76,   62,   65,
      116,  116,  116,  116,  116,   70,   70,  116,  116,  116,
      115,   75,   75,   63,  116,   66,  116,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   64,  116,   67,    4,    4,    1,    4,
        5,    5,    2,    5,    6,    6,    3,    6,  117,    7,
      117,  117,  109,  117,   94,  108,  104,  117,   96,  105,

       98,   83,   83,   83,   95,   95,   95,   97,   97,   97,
       99,   99,  112,   61,    0,    0,  114,   46,   51,    0,
       57,   44,   42,   43,   73,   54,   45,   74,   69,   70,
        0,   71,   70,    0,   55,   58,   60,   59,   56,   75,
       76,   76,  113,   52,   75,    9,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   25,   75,   27,
       28,   75,   32,   75,   75,   75,   75,   75,   75,   75,
       75,   53,    0,    1,    0,    0,    0,    2,    0,    0,
        0,    3,    0,    0,    0,  111,    0,  110,    0,    0,
       94,    0,  100,  100,    0,    0,   93,   77,   79,   81,

       91,   78,   84,   85,   86,   87,   88,   89,   90,   93,
       96,    0,  101,  101,    0,    0,   98,    0,    0,   95,
       80,   82,   97,   80,   82,   99,   76,   47,    0,   73,
       48,   73,    0,   74,   69,    0,   72,   68,   50,   49,
        8,   75,   75,   75,   75,   14,   15,   16,   75,   75,
       75,   75,   75,   22,   75,   75,   75,    0,   30,   75,
       75,   75,   75,   75,   75,   39,   75,   75,    0,    0,
       91,   92,    0,    0,  106,  107,    0,   73,    0,   73,
        0,   74,   72,   68,   75,   75,   75,   75,   17,   18,
       75,   20,   75,   23,   75,   75,    0,    0,   33,   75,

       75,   75,   75,   75,   75,   75,  100,   91,   92,  101,
        0,  102,  102,    0,    0,    0,  103,  103,    0,    0,
        0,   73,   75,   11,   12,   75,   75,   75,   75,   75,
        0,    0,   75,   35,   36,   75,   75,   40,   41,    0,
        0,    0,    0,   10,   75,   19,   75,   24,   26,   29,
       31,   75,   37,   38,  102,  103,   75,   21,   75,   13,
       75,   34,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,    1,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,    1,    1,   20,
       21,   22,   23,    1,   24,   24,   24,   25,   26,   24,
       27,   27,   27,   28,   27,   29,   27,   27,   27,   27,
       27,   30,   27,   27,   27,   27,   27,   31,   27,   27,
       32,   33,   34,   35,   27,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   28,   45,   46,   47,   48,
       49,   50,   27,   51,   52,   53,   54,   55,   56,   57,
       58,   27,   59,   60,   61,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[62] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    1,    5,    5,    5,    1,
        1,    1,    1,    5,    5,    5,    6,    6,    6,    6,
        6,    1,    7,    1,    1,    5,    5,    5,    5,    5,
        5,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    1,    1,
        1
    } ;

static yyconst short int yy_base[392] =
    {   0,
        0,    0,   60,   62,   67,   69,   74,   76,  670,  669,
       81,   83,   85,   88,   89,   91,   90,   92,   97,   98,
      105,  106,  110,  111,  107,  123,  124,  132,  693,  696,
      690,  696,  670,  685,  686,  667,  666,  677,  696,  696,
       84,  664,  663,  117,  126,  151,  135,  106,  662,  124,
      696,    0,  146,  696,  679,  696,  660,  110,  629,  138,
      639,   58,  123,  632,  142,  628,  625,  135,  190,  622,
      623,  630,  628,  696,  650,  696,  696,  198,  696,  667,
      696,  200,  696,  666,  696,  207,  696,  665,  696,  696,
      664,  209,  696,  663,    0,  696,  212,  261,    0,  214,

        0,  660,  696,  655,    0,    0,  213,    0,    0,  215,
        0,  220,  661,  696,  657,  658,  696,  696,  696,  651,
      638,  696,  696,  696,  215,  637,  696,  220,  267,  302,
      239,  696,  696,    0,  636,  696,  696,  696,  635,    0,
      650,  645,  696,  696,  614,  600,  611,  614,  601,  595,
      132,  141,  158,  599,  595,  596,  595,    0,  593,    0,
      640,  588,    0,  588,  187,  595,  585,  601,  578,  591,
      594,  696,  248,  696,  630,  629,  265,  696,  628,  627,
      270,  696,  626,  625,  624,  696,  285,  696,  623,  619,
        0,  299,  616,  606,  231,  604,  696,  696,  696,  696,

      131,  696,  696,  696,  696,  696,  696,  696,  696,    0,
        0,  331,  597,  592,  272,  593,    0,  589,  573,    0,
      696,    0,    0,    0,  696,    0,  696,  696,  338,  696,
      696,  341,  357,  696,  696,  305,  326,  130,  696,  696,
        0,  541,  421,  404,  402,    0,    0,    0,  413,  413,
      411,  412,  413,    0,  401,  410,  397,  226,  443,  392,
      404,  394,  389,  385,  385,    0,  390,  389,  428,  423,
      244,    0,  425,  420,  332,  375,  308,  368,  375,  696,
      380,  383,  696,  696,  376,  380,  372,  379,    0,    0,
      372,    0,  375,    0,  384,  356,  355,  205,    0,  351,

      338,  350,  328,  334,  333,  333,  696,  696,  696,  696,
      401,  363,  357,  294,  360,  407,  348,  340,  301,  344,
      396,  400,  293,    0,    0,  291,  285,  289,  269,  258,
      252,  252,  254,    0,    0,  242,  251,    0,    0,  278,
      271,  270,  260,    0,  205,    0,  177,    0,    0,  696,
      696,  169,    0,    0,  696,  696,  148,    0,  107,    0,
       77,    0,  696,  458,  465,  472,  479,  486,  493,  500,
      507,  514,  521,  528,  535,  538,  544,  551,  558,  565,
      572,  579,  585,  592,  598,  604,  611,  618,   76,   69,
       62

    } ;

static yyconst short int yy_def[392] =
    {   0,
      363,    1,  364,  364,  365,  365,  366,  366,  367,  367,
      368,  368,  369,  369,  370,  370,  371,  371,  371,  371,
      372,  372,  373,  373,  374,  374,  374,  374,  363,  363,
      363,  363,  363,  363,  375,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  376,  376,  363,  363,  363,  363,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  363,  363,  363,  363,  363,  363,  377,
      363,  363,  363,  378,  363,  363,  363,  379,  363,  363,
      380,  380,  363,  381,  382,  363,  363,  383,  384,  363,

      385,  363,  363,  363,  386,  386,  386,  387,  387,  387,
      388,  388,  363,  363,  363,  375,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  389,  363,  363,  363,  363,  363,  376,
      363,  363,  363,  363,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  363,  363,  363,  377,  377,  363,  363,  378,  378,
      363,  363,  379,  379,  380,  363,  380,  363,  381,  381,
      382,  363,  363,  363,  363,  363,  363,  363,  363,  363,

      363,  363,  363,  363,  363,  363,  363,  363,  363,  390,
      384,  363,  363,  363,  363,  363,  385,  363,  363,  386,
      363,  386,  387,  387,  363,  388,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  389,  363,  363,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  363,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  363,  363,
      363,  391,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  363,  363,  376,  376,

      376,  376,  376,  376,  376,  376,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  376,  376,  376,  376,  376,  376,  376,  376,
      363,  363,  376,  376,  376,  376,  376,  376,  376,  363,
      363,  363,  363,  376,  376,  376,  376,  376,  376,  363,
      363,  376,  376,  376,  363,  363,  376,  376,  376,  376,
      376,  376,    0,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363

    } ;

static yyconst short int yy_nxt[758] =
    {   0,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   47,   48,
       49,   50,   51,   52,   52,   52,   52,   52,   52,   53,
       52,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   52,   65,   52,   52,   52,   66,   67,   68,
       69,   70,   71,   52,   52,   72,   52,   73,   74,   75,
       76,   78,   79,   78,   79,   80,  309,   80,   82,   83,
       82,   83,   84,  272,   84,   86,   87,   86,   87,   88,
      238,   88,   92,   93,   92,   93,   94,   96,   94,   97,
       96,   96,   97,   96,  102,  121,  102,  100,  103,  100,

      103,  103,  103,  152,  122,  104,  104,  106,  106,   97,
       97,  102,  109,  109,  153,  103,  362,   98,  100,  100,
       98,   98,   98,   98,   98,  135,  136,  102,  103,   98,
       98,  103,  104,  125,  125,  125,  103,  107,  107,  112,
      104,  126,  110,  110,  138,  139,  127,  271,  271,  128,
      141,  130,  130,  130,  142,  112,  112,  145,  284,  361,
      131,  146,  132,  133,  112,  128,  154,  129,  129,  130,
      164,  155,  247,  156,  131,  284,  131,  248,  132,  133,
      133,  134,  158,  148,  249,  165,  149,  360,  159,  160,
      131,  150,  250,  161,  141,  251,  133,  252,  142,  173,

      174,  177,  178,  175,  359,  179,  298,  134,  181,  182,
      187,  188,  183,  192,  189,  212,  193,  221,  213,  224,
      194,  222,  214,  225,  221,  166,  261,  258,  225,  167,
      262,  125,  125,  125,  358,  193,  232,  232,  232,  194,
      229,  195,  230,  215,  196,  233,  216,  234,  332,  173,
      174,  236,  236,  175,  229,  237,  237,  237,  357,  233,
      308,  308,  195,  198,  215,  199,  177,  178,  356,  200,
      179,  181,  182,  297,  356,  183,  213,  201,  201,  355,
      214,  128,  355,  129,  129,  130,  187,  188,  354,  353,
      189,  352,  131,  202,  132,  235,  203,  204,  312,  351,

      192,  205,  313,  193,  350,  317,  131,  194,  206,  318,
      349,  207,  235,  208,  348,  209,  128,  210,  130,  130,
      130,  237,  237,  237,  278,  278,  278,  131,  195,  132,
      133,  196,  212,  311,  347,  213,  312,  346,  345,  214,
      313,  131,  237,  237,  237,  344,  316,  133,  343,  195,
      277,  277,  342,  283,  278,  278,  278,  232,  232,  232,
      215,  314,  311,  216,  315,  341,  279,  340,  280,  281,
      281,  339,  338,  282,  282,  282,  316,  337,  336,  317,
      279,  215,  314,  318,  278,  278,  278,  321,  321,  335,
      334,  322,  322,  322,  333,  230,  282,  282,  282,  282,

      282,  282,  311,  331,  319,  312,  330,  320,  316,  313,
      234,  317,  322,  322,  322,  318,  322,  322,  322,  329,
      328,  327,  326,  325,  324,  319,  323,  280,  310,  310,
      314,  307,  307,  315,  306,  305,  319,  304,  303,  320,
      302,  301,  300,  299,  298,  296,  295,  294,  293,  292,
      291,  314,  290,  289,  288,  287,  286,  319,   77,   77,
       77,   77,   77,   77,   77,   81,   81,   81,   81,   81,
       81,   81,   85,   85,   85,   85,   85,   85,   85,   89,
       89,   89,   89,   89,   89,   89,   91,   91,   91,   91,
       91,   91,   91,   95,   95,   95,   95,   95,   95,   95,

       99,   99,   99,   99,   99,   99,   99,  101,  101,  101,
      101,  101,  101,  101,  105,  105,  105,  105,  105,  105,
      105,  108,  108,  108,  108,  108,  108,  108,  111,  111,
      111,  111,  111,  111,  111,  116,  116,  116,  116,  116,
      116,  116,  140,  140,  176,  176,  176,  176,  176,  176,
      176,  180,  180,  180,  180,  180,  180,  180,  184,  184,
      184,  184,  184,  184,  184,  185,  185,  185,  185,  185,
      185,  185,  190,  190,  190,  190,  190,  190,  190,  191,
      285,  276,  191,  191,  191,  197,  197,  197,  197,  197,
      197,  197,  211,  275,  211,  212,  211,  211,  217,  217,

      274,  273,  217,  217,  220,  220,  192,  220,  220,  220,
      220,  223,  223,  223,  270,  223,  223,  223,  226,  226,
      269,  188,  226,  226,  226,  188,  186,  182,  182,  178,
      178,  174,  174,  268,  267,  266,  265,  264,  263,  260,
      259,  258,  257,  256,  255,  254,  253,  246,  245,  244,
      243,  242,  241,  120,  115,  240,  239,  231,  228,  227,
      117,  227,  113,  219,  218,  188,  186,  182,  178,  174,
      172,  171,  170,  169,  168,  163,  162,  157,  151,  147,
      144,  143,  137,  124,  123,  120,  119,  118,  117,  115,
      114,  113,  363,   90,   90,   29,  363,  363,  363,  363,

      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363
    } ;

static yyconst short int yy_chk[758] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    4,    4,    3,  391,    4,    5,    5,
        6,    6,    5,  390,    6,    7,    7,    8,    8,    7,
      389,    8,   11,   11,   12,   12,   11,   13,   12,   13,
       14,   15,   14,   16,   17,   41,   18,   15,   17,   16,

       18,   19,   20,   62,   41,   19,   20,   21,   22,   21,
       22,   25,   23,   24,   62,   25,  361,   13,   23,   24,
       14,   15,   17,   16,   18,   48,   48,   26,   27,   19,
       20,   26,   27,   44,   44,   44,   28,   21,   22,   25,
       28,   45,   23,   24,   50,   50,   45,  201,  201,   47,
       53,   47,   47,   47,   53,   26,   27,   58,  238,  359,
       47,   58,   47,   47,   28,   46,   63,   46,   46,   46,
       68,   63,  151,   63,   47,  238,   46,  151,   46,   46,
       47,   46,   65,   60,  152,   68,   60,  357,   65,   65,
       46,   60,  152,   65,   69,  153,   46,  153,   69,   78,

       78,   82,   82,   78,  352,   82,  298,   46,   86,   86,
       92,   92,   86,   97,   92,  100,   97,  107,  100,  110,
       97,  107,  100,  110,  112,   69,  165,  258,  112,   69,
      165,  125,  125,  125,  347,  195,  128,  128,  128,  195,
      125,   97,  125,  100,   97,  128,  100,  128,  298,  173,
      173,  131,  131,  173,  125,  131,  131,  131,  345,  128,
      271,  271,   97,   98,  100,   98,  177,  177,  343,   98,
      177,  181,  181,  258,  342,  181,  215,   98,   98,  341,
      215,  129,  340,  129,  129,  129,  187,  187,  337,  336,
      187,  333,  129,   98,  129,  129,   98,   98,  314,  332,

      192,   98,  314,  192,  331,  319,  129,  192,   98,  319,
      330,   98,  129,   98,  329,   98,  130,   98,  130,  130,
      130,  236,  236,  236,  277,  277,  277,  130,  192,  130,
      130,  192,  212,  275,  328,  212,  275,  327,  326,  212,
      275,  130,  237,  237,  237,  323,  320,  130,  318,  192,
      229,  229,  317,  237,  229,  229,  229,  232,  232,  232,
      212,  275,  315,  212,  275,  313,  232,  312,  232,  233,
      233,  306,  305,  233,  233,  233,  276,  304,  303,  276,
      232,  212,  275,  276,  278,  278,  278,  279,  279,  302,
      301,  279,  279,  279,  300,  278,  281,  281,  281,  282,

      282,  282,  311,  297,  276,  311,  296,  276,  316,  311,
      282,  316,  321,  321,  321,  316,  322,  322,  322,  295,
      293,  291,  288,  287,  286,  276,  285,  322,  274,  273,
      311,  270,  269,  311,  268,  267,  316,  265,  264,  316,
      263,  262,  261,  260,  259,  257,  256,  255,  253,  252,
      251,  311,  250,  249,  245,  244,  243,  316,  364,  364,
      364,  364,  364,  364,  364,  365,  365,  365,  365,  365,
      365,  365,  366,  366,  366,  366,  366,  366,  366,  367,
      367,  367,  367,  367,  367,  367,  368,  368,  368,  368,
      368,  368,  368,  369,  369,  369,  369,  369,  369,  369,

      370,  370,  370,  370,  370,  370,  370,  371,  371,  371,
      371,  371,  371,  371,  372,  372,  372,  372,  372,  372,
      372,  373,  373,  373,  373,  373,  373,  373,  374,  374,
      374,  374,  374,  374,  374,  375,  375,  375,  375,  375,
      375,  375,  376,  376,  377,  377,  377,  377,  377,  377,
      377,  378,  378,  378,  378,  378,  378,  378,  379,  379,
      379,  379,  379,  379,  379,  380,  380,  380,  380,  380,
      380,  380,  381,  381,  381,  381,  381,  381,  381,  382,
      242,  219,  382,  382,  382,  383,  383,  383,  383,  383,
      383,  383,  384,  218,  384,  216,  384,  384,  385,  385,

      214,  213,  385,  385,  386,  386,  196,  386,  386,  386,
      386,  387,  387,  387,  194,  387,  387,  387,  388,  388,
      193,  190,  388,  388,  388,  189,  185,  184,  183,  180,
      179,  176,  175,  171,  170,  169,  168,  167,  166,  164,
      162,  161,  159,  157,  156,  155,  154,  150,  149,  148,
      147,  146,  145,  142,  141,  139,  135,  126,  121,  120,
      116,  115,  113,  104,  102,   94,   91,   88,   84,   80,
       75,   73,   72,   71,   70,   67,   66,   64,   61,   59,
       57,   55,   49,   43,   42,   38,   37,   36,   35,   34,
       33,   31,   29,   10,    9,  363,  363,  363,  363,  363,

      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "pcl-lexer.l"
#define INITIAL 0
/* PCL - Predicate Constraint Language
 * Copyright (C) 2006 The Boeing Company
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 */
#line 20 "pcl-lexer.l"
#include "pcl.h"
#include "pcl-node.h"
#include "pcl-parser.h" /* generated by Bison */
#include "glib-ext.h"   /* only until GLib 2.10 */

#ifdef HAVE_LIBREADLINE

#include <readline/readline.h>
#include <readline/history.h>

#include <setjmp.h>
#include <signal.h>

/* see comments in lexer_input() */
static jmp_buf env;

static void
lexer_signal_handler (gint sig)
{
        longjmp (env, 1);
}

#endif /* HAVE_LIBREADLINE */

#define E_DEDENT        "unindent does not match any outer indentation level"
#define E_EOLS          "EOL while scanning single-quoted string"
#define E_TOKEN         "invalid token"
#define E_TOODEEP       "too many levels of indentation"

#define MAXINDENT       100     /* max indentation level */
#define TABSIZE         8       /* # spaces per tab char */

/* borrowed from the parser */
#define NEW_TREE_NODE(type, loc) \
        g_node_new (pcl_node_new ( \
        (type), (loc).first_line, (loc).first_column))

#define YY_INPUT(buffer, result, max_size) \
        result = lexer_input ((buffer), (max_size))

/* YY_USER_ACTION is always executed prior to the matched rule's action.
 * If there are pending DEDENT tokens to be issued, put the matched text
 * back in the input stream to be rescanned on the next pass.  Otherwise
 * update the parser location variable `yylloc'. */
#define YY_USER_ACTION  \
        if (pending_dedents > 0) \
        { \
                yyless (0); \
                pending_dedents--; \
                return DEDENT; \
        } \
        lexer_update_yylloc ();

/* Global Variables */
static const gchar *input_name = NULL;
static const gchar *cur_prompt = NULL;
static const gchar *alt_prompt = NULL;
static GString *string_buffer = NULL;
static gint eof_token = YY_NULL;
static gint error_code = 0;
static gint in_enclosure = 0;
static gint indent_level = 0;
static gint pending_dedents = 0;
static gint indent_stack[MAXINDENT] = { 0 };
static gboolean is_interactive = FALSE;

/* Parser Declarations */
extern gint yychar;
extern YYLTYPE yylloc;
extern gint yyparse (void);

/* Forward Declarations */
static gint lexer_start (gint token);
static gint lexer_input (gchar *buffer, gsize max_size);
static gint lexer_flush (void);
static gint lexer_indent (const gchar *text);
static gint lexer_process_float (gchar *text, gint length);
static gint lexer_process_integer (gchar *text, gint length);
static gint lexer_process_string (gchar *text);
static gint lexer_process_name (gchar *text);
static void lexer_update_yylloc (void);
static void lexer_quoted_begin (const gchar *text);
static void lexer_quoted_concat (const gchar *text);
static void lexer_quoted_append_chr (gchar c);
static void lexer_quoted_append_hex (const gchar *hex);
static void lexer_quoted_append_oct (const gchar *oct);
static void lexer_quoted_append_str (const gchar *str);
static void lexer_quoted_push_state (const gchar *text);
static gint lexer_quoted_end (void);
gint yyerror (const gchar *message);
#define YY_STACK_USED 1
#define EIN 1
#define FIN 2
#define SIN 3
#define FLUSH 4
#define BOL 5

#define DQ 6
#define SQ 7
#define TDQ 8
#define TSQ 9
#define RDQ 10
#define RSQ 11
#define RTDQ 12
#define RTSQ 13

#line 782 "pcl-lexer.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 125 "pcl-lexer.l"


#line 936 "pcl-lexer.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 364 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 696 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 127 "pcl-lexer.l"
/* whitespace - do nothing */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 128 "pcl-lexer.l"
/* whitespace - do nothing */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 129 "pcl-lexer.l"
/* whitespace - do nothing */
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 130 "pcl-lexer.l"
return lexer_start (EVAL_INPUT);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 131 "pcl-lexer.l"
return lexer_start (FILE_INPUT);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 132 "pcl-lexer.l"
return lexer_start (SINGLE_INPUT);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 134 "pcl-lexer.l"
return DEDENT;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 136 "pcl-lexer.l"
return KW_AND;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 137 "pcl-lexer.l"
return KW_AS;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 138 "pcl-lexer.l"
return KW_ASSERT;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 139 "pcl-lexer.l"
return KW_BREAK;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 140 "pcl-lexer.l"
return KW_CLASS;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 141 "pcl-lexer.l"
return KW_CONTINUE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 142 "pcl-lexer.l"
return KW_CUT;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 143 "pcl-lexer.l"
return KW_DEF;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 144 "pcl-lexer.l"
return KW_DEL;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 145 "pcl-lexer.l"
return KW_ELIF;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 146 "pcl-lexer.l"
return KW_ELSE;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 147 "pcl-lexer.l"
return KW_EXCEPT;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 148 "pcl-lexer.l"
return KW_EXEC;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 149 "pcl-lexer.l"
return KW_FINALLY;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 150 "pcl-lexer.l"
return KW_FOR;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 151 "pcl-lexer.l"
return KW_FROM;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 152 "pcl-lexer.l"
return KW_GLOBAL;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 153 "pcl-lexer.l"
return KW_IF;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 154 "pcl-lexer.l"
return KW_IMPORT;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 155 "pcl-lexer.l"
return KW_IN;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 156 "pcl-lexer.l"
return KW_IS;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 157 "pcl-lexer.l"
return KW_IS_NOT;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 158 "pcl-lexer.l"
return KW_NOT;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 159 "pcl-lexer.l"
return KW_NOT_IN;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 160 "pcl-lexer.l"
return KW_OR;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 161 "pcl-lexer.l"
return KW_PASS;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 162 "pcl-lexer.l"
return KW_PREDICATE;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 163 "pcl-lexer.l"
return KW_PRINT;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 164 "pcl-lexer.l"
return KW_RAISE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 165 "pcl-lexer.l"
return KW_RETURN;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 166 "pcl-lexer.l"
return KW_STATIC;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 167 "pcl-lexer.l"
return KW_TRY;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 168 "pcl-lexer.l"
return KW_WHILE;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 169 "pcl-lexer.l"
return KW_YIELD;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 171 "pcl-lexer.l"
return OP_INPLACE_ADD;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 172 "pcl-lexer.l"
return OP_INPLACE_SUB;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 173 "pcl-lexer.l"
return OP_INPLACE_MUL;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 174 "pcl-lexer.l"
return OP_INPLACE_DIV;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 175 "pcl-lexer.l"
return OP_INPLACE_MOD;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 176 "pcl-lexer.l"
return OP_INPLACE_POW;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 177 "pcl-lexer.l"
return OP_INPLACE_FLD;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 178 "pcl-lexer.l"
return OP_INPLACE_LSH;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 179 "pcl-lexer.l"
return OP_INPLACE_RSH;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 180 "pcl-lexer.l"
return OP_INPLACE_AND;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 181 "pcl-lexer.l"
return OP_INPLACE_XOR;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 182 "pcl-lexer.l"
return OP_INPLACE_OR;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 183 "pcl-lexer.l"
return OP_FLD;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 184 "pcl-lexer.l"
return OP_LSH;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 185 "pcl-lexer.l"
return OP_RSH;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 186 "pcl-lexer.l"
return OP_POW;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 187 "pcl-lexer.l"
return OP_LE;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 188 "pcl-lexer.l"
return OP_GE;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 189 "pcl-lexer.l"
return OP_EQ;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 190 "pcl-lexer.l"
return OP_NE;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 192 "pcl-lexer.l"
in_enclosure++; return yytext[0];
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 193 "pcl-lexer.l"
in_enclosure++; return yytext[0];
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 194 "pcl-lexer.l"
in_enclosure++; return yytext[0];
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 195 "pcl-lexer.l"
in_enclosure--; return yytext[0];
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 196 "pcl-lexer.l"
in_enclosure--; return yytext[0];
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 197 "pcl-lexer.l"
in_enclosure--; return yytext[0];
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 199 "pcl-lexer.l"
return lexer_process_integer (yytext, yyleng);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 200 "pcl-lexer.l"
return lexer_process_integer (yytext, yyleng);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 201 "pcl-lexer.l"
return lexer_process_integer (yytext, yyleng);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 202 "pcl-lexer.l"
return lexer_process_integer (yytext, yyleng);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 204 "pcl-lexer.l"
return lexer_process_float (yytext, yyleng);
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 205 "pcl-lexer.l"
return lexer_process_float (yytext, yyleng);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 206 "pcl-lexer.l"
return lexer_process_float (yytext, yyleng);
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 208 "pcl-lexer.l"
return lexer_process_name (yytext);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 210 "pcl-lexer.l"
lexer_quoted_begin (yytext);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 211 "pcl-lexer.l"
/* escaped newline - do nothing */
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 212 "pcl-lexer.l"
lexer_quoted_append_chr ('\\');
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 213 "pcl-lexer.l"
lexer_quoted_append_chr ('"');
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 214 "pcl-lexer.l"
lexer_quoted_append_str (yytext);
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 215 "pcl-lexer.l"
lexer_quoted_append_chr ('\'');
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 216 "pcl-lexer.l"
lexer_quoted_append_str (yytext);
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 217 "pcl-lexer.l"
lexer_quoted_append_str (yytext);
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 218 "pcl-lexer.l"
lexer_quoted_append_chr ('\a');
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 219 "pcl-lexer.l"
lexer_quoted_append_chr ('\b');
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 220 "pcl-lexer.l"
lexer_quoted_append_chr ('\f');
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 221 "pcl-lexer.l"
lexer_quoted_append_chr ('\n');
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 222 "pcl-lexer.l"
lexer_quoted_append_chr ('\r');
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 223 "pcl-lexer.l"
lexer_quoted_append_chr ('\t');
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 224 "pcl-lexer.l"
lexer_quoted_append_chr ('\v');
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 225 "pcl-lexer.l"
lexer_quoted_append_oct (&yytext[1]);
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 226 "pcl-lexer.l"
lexer_quoted_append_hex (&yytext[2]);
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 227 "pcl-lexer.l"
lexer_quoted_append_chr (yytext[1]);
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 228 "pcl-lexer.l"
lexer_quoted_append_str (yytext);
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 229 "pcl-lexer.l"
lexer_quoted_append_str (yytext);
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 230 "pcl-lexer.l"
lexer_quoted_append_str (yytext);
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 231 "pcl-lexer.l"
lexer_quoted_append_str (yytext);
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 232 "pcl-lexer.l"
lexer_quoted_append_str (yytext);
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 233 "pcl-lexer.l"
lexer_quoted_append_str (yytext);
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 234 "pcl-lexer.l"
lexer_quoted_concat (&yytext[1]);
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 235 "pcl-lexer.l"
lexer_quoted_concat (&yytext[1]);
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 236 "pcl-lexer.l"
lexer_quoted_concat (&yytext[3]);
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 237 "pcl-lexer.l"
lexer_quoted_concat (&yytext[3]);
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 238 "pcl-lexer.l"
return lexer_quoted_end ();
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 239 "pcl-lexer.l"
return lexer_quoted_end ();
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 240 "pcl-lexer.l"
return lexer_quoted_end ();
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 241 "pcl-lexer.l"
return lexer_quoted_end ();
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 242 "pcl-lexer.l"
{ yylloc.first_column--;
                                  return yyerror (E_EOLS); }
	YY_BREAK
case YY_STATE_EOF(DQ):
case YY_STATE_EOF(SQ):
case YY_STATE_EOF(RDQ):
case YY_STATE_EOF(RSQ):
#line 244 "pcl-lexer.l"
{ yylloc.first_column--;
                                  return yyerror (E_EOLS); }
	YY_BREAK
case YY_STATE_EOF(TDQ):
case YY_STATE_EOF(TSQ):
case YY_STATE_EOF(RTDQ):
case YY_STATE_EOF(RTSQ):
#line 246 "pcl-lexer.l"
{ yylloc.first_column--;
                                  return yyerror (E_EOLS); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 249 "pcl-lexer.l"
{ if (is_interactive && lexer_flush ())
                                  return eof_token; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 251 "pcl-lexer.l"
/* whitespace - do nothing */
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 252 "pcl-lexer.l"
{ gint token = lexer_indent (yytext);
                                  if (token >= 0) return token; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 255 "pcl-lexer.l"
/* whitespace - do nothing */
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 256 "pcl-lexer.l"
/* escaped newline - do nothing */
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 257 "pcl-lexer.l"
{ if (!in_enclosure) {
                                  yy_push_state (BOL); return NEWLINE; } }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 260 "pcl-lexer.l"
return yyerror (E_TOKEN);
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 261 "pcl-lexer.l"
return (gint) yytext[0];
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(EIN):
case YY_STATE_EOF(FIN):
case YY_STATE_EOF(SIN):
case YY_STATE_EOF(FLUSH):
case YY_STATE_EOF(BOL):
#line 263 "pcl-lexer.l"
if (lexer_flush ()) return eof_token;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 265 "pcl-lexer.l"
ECHO;
	YY_BREAK
#line 1633 "pcl-lexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 364 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 364 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 363);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 265 "pcl-lexer.l"


const gint PCL_EVAL_INPUT = EIN;
const gint PCL_FILE_INPUT = FIN;
const gint PCL_SINGLE_INPUT = SIN;

static gint
lexer_start (gint token)
{
        /* GNU Bison only supports a single start rule, but we need more than
         * one to support different kinds of input (eval, file, or single).
         * To get around this limitation, we fake multiple start rules by
         * doing a little dance where the lexer is placed in the appropriate
         * "start" mode before calling yyparse().  In each of these start modes
         * we match any ol' character, put it back in the input stream to be
         * rescanned on the next pass, exit "start" mode, and return the
         * appropriate start token to the parser.  The parser uses the start
         * token to activate the appropriate top-level grammar rules. */

        yyless (0);
        yy_pop_state ();
        yy_push_state (BOL);
        if (token == SINGLE_INPUT)
                eof_token = NEWLINE;
        else
                eof_token = YY_NULL;
        return token;
}

static gint
lexer_input (gchar *buffer, gsize max_size)
{
        gint num_chars_read;

        if (is_interactive)
        {
#ifdef HAVE_LIBREADLINE
                /* You may be wondering what the hell is up with the setjmp()
                 * call.  GNU Readline doesn't handle signals the way we would
                 * like.  We would like for the user to hit ^C during keyboard
                 * input and have that generate a KeyboardInterrupt exception.
                 * Normally (see the non-readline version of this below) we
                 * would install a SIGINT handler that logs an interrupt in
                 * the signal module and causes the input-reading function
                 * (e.g. fgets) to fail and set errno to EINTR to indicate
                 * that an interrupt occurred.  But that won't work in this
                 * case.  Readline's manual states:
                 *
                 *    If and when the calling application's signal handler
                 *    returns, Readline will reinitialize the terminal and
                 *    continue to accept input.
                 * 
                 * But we don't want to continue accepting input, so we need a
                 * way to prevent our signal handling function from returning
                 * back into the readline() call.  To do this we install a
                 * temporary SIGINT handler.  The SIGINT handler simply calls
                 * longjmp() to force the instruction pointer to a jump point
                 * that we establish here with the setjmp() call.  Upon
                 * jumping, setjmp() will return a non-zero value, dropping us
                 * into the "if" block where we can then perform our *real*
                 * signal handling logic.
                 *
                 * XXX Also, it would seem that Readline also blocks SIGINT.
                 *     So we need to unblock than when handling a SIGINT.
                 */

                static gboolean rl_init = FALSE;
                struct sigaction sa_temp, sa_save;
                gchar *line;

                /* readline initialization */
                if (G_UNLIKELY (!rl_init))
                {
                        rl_instream = yyin;
                        rl_outstream = yyout;

                        /* disable TAB completion */
                        rl_bind_key ('\t', rl_insert);

                        rl_init = TRUE;
                }

                sa_temp.sa_handler = lexer_signal_handler;
                sigemptyset (&sa_temp.sa_mask);
                sa_temp.sa_flags = 0;

                /* XXX not checking return value */
                sigaction (SIGINT, &sa_temp, &sa_save);

                if (setjmp (env))
                {
                        sigset_t signal_mask;

                        /* unblock SIGINT */
                        sigemptyset (&signal_mask);
                        sigaddset (&signal_mask, SIGINT);
                        sigprocmask (SIG_UNBLOCK, &signal_mask, NULL);

                        /* XXX not checking return value */
                        sigaction (SIGINT, &sa_save, NULL);

                        pcl_error_set_interrupt ();
                        pcl_error_check_signals ();
                        goto except;
                }

                line = readline (cur_prompt);

                /* XXX not checking return value */
                sigaction (SIGINT, &sa_save, NULL);

                if (line == NULL)
                {
                        error_code = PCL_ERROR_EOF;
                        goto except;
                }
                if (*line != '\0')
                        add_history (line);

                /* XXX double-buffering the input */
                g_strlcpy (buffer, line, max_size - 1);
                g_strlcat (buffer, "\n", max_size);
                free (line);  /* not g_free() */

#else           /* --- the non-readline version --- */

                errno = 0;
                fputs (cur_prompt, yyout);
                if (fgets (buffer, (gint) max_size, yyin) == NULL)
                {
                        if (feof (yyin))
                        {
                                error_code = PCL_ERROR_EOF;
                                goto except;
                        }
                        if (errno == EINTR)
                        {
                                /* XXX Skipping some thread stuff. */
                                if (!pcl_error_check_signals ())
                                        goto except;
                        }
                        if (pcl_os_interrupt_occurred ())
                                goto except;
                        g_error ("%s: fgets() failed", G_STRFUNC);
                }

#endif /* HAVE_LIBREADLINE */
                num_chars_read = strlen (buffer);
                if (num_chars_read > 1)
                        cur_prompt = alt_prompt;
        }
        else
        {
                errno = 0;
                num_chars_read = fread (buffer, 1, max_size, yyin);
                while (ferror (yyin))
                {
                        if (errno != EINTR)
                                g_error ("%s: fread() failed", G_STRFUNC);
                        errno = 0;
                        clearerr (yyin);
                        num_chars_read = fread (buffer, 1, max_size, yyin);
                }
        }

        return num_chars_read;

except:

        fputc ('\n', yyout);
        return 0;
}

static gint
lexer_flush (void)
{
        /* If the last line of the input buffer is indented, we find ourselves
         * in a situation where the lexer has no more source code to read, but
         * the parser is still expecting DEDENT tokens.  So we have to somehow
         * "flush" the lexer of all pending DEDENT tokens.
         *
         * To do with this we set the lexer to 'FLUSH' mode and switch to a
         * new input buffer consisting of a single character for each pending
         * DEDENT token to be returned to the parser.  For example, if the
         * parser is expecting three DEDENT tokens, we switch to an input
         * buffer consisting of the string 'DDD'.  The number of DEDENT tokens
         * to be returned is determined from the indentation level.  When the
         * new input buffer is exhausted, we come back to this function to
         * free up resources and put the lexer back in it's initial mode. */

        static YY_BUFFER_STATE buffer = NULL;
        static gchar base[MAXINDENT + 8];  /* leave room for EOB chars */

        if (buffer != NULL)
        {
                /* second pass */
                g_assert (YY_START == FLUSH);
                yy_delete_buffer (buffer);
                yy_pop_state ();
                buffer = NULL;
        }
        else if (indent_level > 0)
        {
                /* first pass */
                gchar *cp = base;
                while (indent_level-- > 0)
                        *cp++ = 'D';
                *cp++ = YY_END_OF_BUFFER_CHAR;
                *cp++ = YY_END_OF_BUFFER_CHAR;
                g_assert (cp - base < sizeof (base));
                buffer = yy_scan_buffer (base, cp - base);
                g_assert (buffer != NULL);
                yy_push_state (FLUSH);
        }

        return (buffer == NULL);
}

static gint
lexer_indent (const gchar *text)
{
        gint indent = 0;
        gint whitespace = 0;
        const gchar *cp = text;

        g_assert (pending_dedents == 0);

        /* ignore formfeed */
        if (*cp == '\f')
        {
                whitespace++;
                cp++;
        }

        /* calculate whitespace and indentation level */
        while (*cp == ' ' || *cp == '\t')
        {
                if (*cp++ == '\t')
                        indent += TABSIZE - indent % TABSIZE;
                else
                        indent++;
                whitespace++;
        }

        /* put back everything after the whitespace */
        yy_pop_state ();
        yylloc.last_line--;
        yylloc.last_column = whitespace;
        yyless (whitespace);

        /* indent */
        if (indent > indent_stack[indent_level])
        {
                if (indent_level >= MAXINDENT)
                {
                        yylloc.first_column = yylloc.last_column;
                        return yyerror (E_TOODEEP);
                }
                indent_stack[++indent_level] = indent;
                return INDENT;
        }

        /* dedent */
        if (indent < indent_stack[indent_level])
        {
                while (indent < indent_stack[indent_level])
                {
                        indent_level--;
                        pending_dedents++;
                }
                if (indent != indent_stack[indent_level])
                {
                        yylloc.first_column = yylloc.last_column;
                        return yyerror (E_DEDENT);
                }
                pending_dedents--;
                return DEDENT;
        }

        return -1;  /* success -- no token */
}

static gint
lexer_process_float (gchar *text, gint length)
{
        PclNodeType type;
        gchar last = text[length - 1];

        if (last == 'j' || last == 'J')
                type = PCL_NODE_TYPE_IMAGINARY;
        else
                type = PCL_NODE_TYPE_FLOAT;
        yylval.node = NEW_TREE_NODE (type, yylloc);
        PCL_NODE_STRING (yylval.node) = g_strdup (text);
        return NUMBER;
}

static gint
lexer_process_integer (gchar *text, gint length)
{
        PclNodeType type;
        gchar last = text[length - 1];

        if (last == 'j' || last == 'J')
                type = PCL_NODE_TYPE_IMAGINARY;
        else
                type = PCL_NODE_TYPE_INTEGER;
        yylval.node = NEW_TREE_NODE (type, yylloc);
        PCL_NODE_STRING (yylval.node) = g_strdup (text);
        return NUMBER;
}

static gint
lexer_process_string (gchar *text)
{
        yylval.node = NEW_TREE_NODE (PCL_NODE_TYPE_STRING, yylloc);
        PCL_NODE_STRING (yylval.node) = g_strdup (text);
        return STRING;
}

static gint
lexer_process_name (gchar *text)
{
        yylval.node = NEW_TREE_NODE (PCL_NODE_TYPE_NAME, yylloc);
        PCL_NODE_STRING (yylval.node) = g_intern_string (text);
        PCL_NODE_FLAGS (yylval.node) = PCL_NODE_FLAG_INTERNED;
        return NAME;
}

static void
lexer_update_yylloc (void)
{
        gchar *cp = yytext;
        gchar *bol = NULL;

        yylloc.first_line = yylloc.last_line;
        yylloc.first_column = yylloc.last_column;

        while (*cp != 0)
                if (*cp++ == '\n')
                {
                        bol = cp;
                        yylloc.last_line++;
                }
        if (bol != NULL)
                yylloc.last_column = cp - bol;
        else
                yylloc.last_column += yyleng;
}

static void
lexer_quoted_begin (const gchar *text)
{
        lexer_quoted_push_state (text);
        if (string_buffer == NULL)
                string_buffer = g_string_sized_new (0x4000);  /* 16K */
        else
                g_string_set_size (string_buffer, 0);
}

static void
lexer_quoted_concat (const gchar *text)
{
        yy_pop_state ();
        lexer_quoted_push_state (text);
}

static void
lexer_quoted_append_chr (gchar c)
{
        g_string_append_c (string_buffer, c);
}

static void
lexer_quoted_append_hex (const gchar *hex)
{
        guint p = 0;
        sscanf (hex, "%x", &p);
        lexer_quoted_append_chr ((gchar) p & 0xFF);
}

static void
lexer_quoted_append_oct (const gchar *oct)
{
        guint p = 0;
        sscanf (oct, "%o", &p);
        lexer_quoted_append_chr ((gchar) p & 0xFF);
}

static void
lexer_quoted_append_str (const gchar *str)
{
        g_string_append (string_buffer, str);
}

static void
lexer_quoted_push_state (const gchar *text)
{
        gint raw = 0;
        gint quotes = 0;
        const gchar *cp = text;

        while (*cp != '\0')
        {
                switch (*cp++)
                {
                        case 'r':
                        case 'R':
                                raw++;
                                break;
                        case '\'':
                                quotes++;
                                break;
                        case '"':
                                quotes--;
                                break;

                        /* skip whitespace */
                }
        }

        g_assert (ABS (quotes) == 1 || ABS (quotes) == 3);

        switch (quotes)
        {
                case -1:  /*  "  */
                        yy_push_state (raw ? RDQ : DQ);
                        break;
                case +1:  /*  '  */
                        yy_push_state (raw ? RSQ : SQ);
                        break;
                case -3:  /* """ */
                        yy_push_state (raw ? RTDQ : TDQ);
                        break;
                case +3:  /* ''' */
                        yy_push_state (raw ? RTSQ : TSQ);
                        break;
        }
}

static gint
lexer_quoted_end (void)
{
        yy_pop_state ();
        return lexer_process_string (string_buffer->str);
}

gint
yyerror (const gchar *message)
{
        g_debug ("(%s) %s", G_STRFUNC, message);

        if (pcl_error_occurred ())
        {
                /* Don't overwrite existing errors. */
                g_debug ("(%s) Skipping due to existing error", G_STRFUNC);
        }
        else
        {
                PclObject *tuple;

                switch (yychar)
                {
                        case INDENT:
                                yylloc.first_column = yylloc.last_column;
                                message = "unexpected indent";
                                break;
                        case DEDENT:
                                yylloc.first_column = yylloc.last_column;
                                message = "unexpected unindent";
                                break;
                        default:
                                message = "invalid syntax";
                                break;
                }

                tuple = pcl_build_value ("(siis)",
                        input_name,
                        yylloc.first_line,
                        yylloc.first_column,
                        message);
                pcl_error_set_object (pcl_exception_syntax_error (), tuple);
                pcl_object_unref (tuple);
        }

        return YY_NULL;
}

static PclParseInfo *
parse_input_common (gint start)
{
        PclParseInfo *parse_info = pcl_parse_info_new (input_name);

        error_code = 0;
        in_enclosure = 0;
        indent_level = 0;
        pending_dedents = 0;
        indent_stack[0] = 0;

        yylloc.first_line = yylloc.last_line = 1;
        yylloc.first_column = yylloc.last_column = 0;

        yy_push_state (start);
        if (yyparse () == 0)
        {
                /* embed input name in root node */
                GNode *parse_tree = yylval.node;
                parse_info->parse_tree = parse_tree;
                parse_info->error_code = error_code;
                PCL_NODE_STRING (parse_tree) = g_strdup (input_name);
        }

        if (YY_START == FLUSH)
                lexer_flush ();

        /* reset lexer */
        while (YY_START != INITIAL)
                yy_pop_state ();

        if (pcl_error_occurred ())
        {
                pcl_parse_info_destroy (parse_info);
                return NULL;
        }

        return pcl_parse_info_normalize (parse_info);
}

PclParseInfo *
pcl_parse_input_file (FILE *stream, const gchar *filename, gint start)
{
        PclParseInfo *parse_info;
        YY_BUFFER_STATE buffer;

        is_interactive = isatty (fileno (stream));
        input_name = (filename != NULL) ? filename : "?";
        buffer = yy_create_buffer (stream, YY_BUF_SIZE);
        yy_switch_to_buffer (buffer);
        parse_info = parse_input_common (start);
        yy_delete_buffer (buffer);
        input_name = NULL;
        return parse_info;
}

PclParseInfo *
pcl_parse_input_file_with_prompts (FILE *stream, const gchar *filename,
                                   gint start, const gchar *ps1,
                                   const gchar *ps2)
{
        PclParseInfo *parse_info;
        cur_prompt = ps1, alt_prompt = ps2;
        parse_info = pcl_parse_input_file (stream, filename, start);
        cur_prompt = alt_prompt = NULL;
        return parse_info;
}

PclParseInfo *
pcl_parse_input_string (const gchar *string, gint start)
{
        PclParseInfo *parse_info;
        YY_BUFFER_STATE buffer;
        GString *bytes;

        is_interactive = FALSE;
        input_name = "<string>";
        bytes = g_string_new (string);
        g_string_append_c (bytes, '\n');
        g_string_append_c (bytes, YY_END_OF_BUFFER_CHAR);
        g_string_append_c (bytes, YY_END_OF_BUFFER_CHAR);
        buffer = yy_scan_buffer (bytes->str, bytes->len);
        parse_info = parse_input_common (start);
        yy_delete_buffer (buffer);
        g_string_free (bytes, TRUE);
        input_name = NULL;
        return parse_info;
}
